version: "3.8"
services:
  mysql:
    image: mysql:latest
    env_file: .env
    ports:
      - 3306:3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=default --execute \"SHOW DATABASES;\""
      timeout: 10s
      retries: 10
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      mysql:
        condition: service_healthy
  phpmyadmin:
    image: phpmyadmin:latest
    env_file: .env
    depends_on:
      - mysql
    ports:
      - 8000:80