version: "3.8"
services:
  mysql:
    image: mysql:latest
    env_file: .env
    ports:
      - 3306:3306
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  phpmyadmin:
    image: phpmyadmin:latest
    env_file: .env
    depends_on:
      - mysql
    ports:
      - 8000:80